### ISSUE TITLE
Tangent invalid float assert on native Windows

### ISSUE THREAD

**Issue by Pombal** [AmbientRun/Ambient#971]
When loading tangent on Windows, an assert triggers before anything is visible on screen: physx-sys-0.8.2\PhysX\physx\source\foundation\include\windows/PsWindowsInlineAoS.h(669) : Assertion failed: isValidFloatV(b)

This is after the log message: "Finished loading module tangent_level_cubicide_server"

This is the call stack:
![image](https://github.com/AmbientRun/Ambient/assets/526714/816fa19a-afaa-42fd-be84-29bccdee5973)

Asking for opinions on the general way to debug these kinds of issues. Since our code is distributed in packages and entities don't contain recognizable identifiers, I can't tell what actor or collider is causing the problem and where it originated from.

@philpax Any ideas?

**Comment by philpax** [comment]
Well, that's quite strange. Unfortunately, we don't have great tools for debugging this kind of thing - and we should, for sure - but for now, the best thing you can do is log the incoming values or use a debugger, and try to find what the problematic values are.

@FredrikNoren What do you normally do in these circumstances?

**Comment by Pombal** [comment]
Yeah, I am using a debugger but the architecture of our code doesn't seem suited for gathering information under a debugger.
This scenario is just an example. So I'm wondering what others tipically do.

**Comment by philpax** [comment]
It's a good question. 

I personally log with enough information until I can reproduce the issue (on both the guest and host) and/or insert asserts at suspect locations where there's enough context. We generally try to make the diagnostics for errors convey their context/location, so it's possible to figure out what caused a particular error from the error alone (i.e. `entity {id}'s component {component} had invalid value {value}`), but that's not always easy/possible.

PhysX has unfortunately been one of the harder areas to protect, because it's very easy to "use it wrong" (compared to Rust), and it's not always clear what the contracts are between various bits of state.

**Comment by Pombal** [comment]
Thanks, that's helpful.

As for this specific issue, I can tell that the problem comes from level_cubicide. The problem doesn't happen if we don't spawn either the cubes or the ground. But it's not specific to either so it seems to come from an interaction between them.
Since you're more familiar with the code, perhaps that's enough for you to have an idea? If not, I'll continue to debug.

**Comment by Pombal** [comment]
Thanks for the context!

For this specific case, I've narrowed it down to an interaction between the cubes and the ground in level_cubicide. Not spawning one or the other doesn't trigger the assert.

**Comment by philpax** [comment]
Hmmm... so the cubes are made to clip into the ground, but they're static, so they shouldn't cause any of the usual physics conflicts (assuming that PhysX isn't generating collision events for them, of course)

#980 makes some level design changes, but nothing too severe, so I imagine the issue will still occur there. I haven't seen it happen on macOS or with my brief Windows testing, so it's curious/concerning that it's happening for you specifically.

Can you try the `tangent-0.2` branch / `main` in ~40 minutes with this diff?

```diff
diff --git a/guest/rust/packages/games/tangent/mods/level_cubicide/src/server.rs b/guest/rust/packages/games/tangent/mods/level_cubicide/src/server.rs
index de9c6c1cd..47f64e665 100644
--- a/guest/rust/packages/games/tangent/mods/level_cubicide/src/server.rs
+++ b/guest/rust/packages/games/tangent/mods/level_cubicide/src/server.rs
@@ -77,7 +77,7 @@ pub async fn main() {
 fn make_cubes(rng: &mut dyn rand::RngCore, grid: &mut Grid) {
     const TARGET_CUBE_COUNT: usize = 500;
     const CUBE_MIN_SIZE: Vec3 = vec3(0.5, 0.5, 2.0);
-    const CUBE_MAX_SIZE: Vec3 = vec3(7., 8., 30.);
+    const CUBE_MAX_SIZE: Vec3 = vec3(1.0, 1.0, 30.);
     const FADE_DISTANCE: f32 = 2.;
 
     let bright_colors = [vec4(0.5921569, 0.78039217, 0.8509804, 1.0)];
@@ -113,7 +113,7 @@ fn make_cubes(rng: &mut dyn rand::RngCore, grid: &mut Grid) {
             continue;
         }
 
-        let position_offset = vec3(0.0, 0.0, -CUBE_MIN_SIZE.z * 0.6);
+        let position_offset = vec3(0.0, 0.0, 10.0);
 
         let accent_sample = rng.gen::<f32>();
         let color = if accent_sample > 0.3 {
@@ -256,7 +256,7 @@ fn make_cube(pos: Vec3, size: Vec3, dynamic: bool, color: Vec4, rng: &mut dyn Rn
     const MASS_MULTIPLIER: f32 = 10.;
 
     let volume = size.dot(Vec3::ONE);
-    let pitch_amplitude: f32 = if dynamic { 5. } else { 60. };
+    let pitch_amplitude: f32 = 0.0;
     Entity::new()
         .with(cube(), ())
         .with(cast_shadows(), ())
```

That should remove all of the clipping, so we can see if that's causing the issue.

**Comment by Pombal** [comment]
The problem isn't deterministic so you may have to try more often, I'd say it happens 7/10 times.

I just tried that diff in main and it doesn't make a difference.

**Comment by philpax** [comment]
Interesting... I'm out of ideas. I've merged in the new version of Tangent now, so you can try that, but I don't imagine it'd be any better :/

Looking at the error from the PhysX end of things, do you know what's invalid about the value and where it's coming from? The callstack suggests that it's from its AABB tree while adding the boxes (the rigid static) - do one of the boxes have a NaN or something in their transform?

**Comment by Pombal** [comment]
Yes, {inf, inf, inf, inf} bounds are returned from computePlaneBounds in the PxGeometryType::ePLANE case in PhysX\physx\source\geomutils\src\GuBounds.cpp

Changing the set_local_pose value in the ColliderDef::Plane case in collider.rs helps but of course breaks tangent which expects those values.

It's still not clear to me why this is not deterministic. PhysX 5 code seems unchanged.

**Comment by Pombal** [comment]
I updated to latest tangent and the problem is gone. Bizarre.
At least it led me to upgrade the debugging workflows on Windows. Using cppvsdbg instead of lldb is faster and more accurate.
